swagger: "2.0"
info: 
    title: Alibazon Ecommerce
    description: This is my Ecommerce Application for OSF Academy
    version: 1.0
    contact: 
        email: angelo.lop.alv@gmail.com 
    license:
        name: Apache 2.0
        url: "http://apache.org/"
    servers:
        -url: "http://localhost:3000/"
        description: This is my local server

schemes: [http, https]

paths:
    /:
        get:
            summary: Returns the page of the men's category
            description: Men's category of Alibazon
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /category/{categoryId}:
        get:
            summary: Returns the page of the category selected
            description: Category of clothes chosen from Alibazon
            parameters:
              - name: categoryId
                in: path
                required: true
                description: The category of the clothes chosen
                schema:
                    type: string
                    minimum: 1        
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /products/{subcategoryId}:
        get:
            summary: Return the product catalog of the subcategory selected
            description: Catalog of products
            parameters:
              - name: subcategoryId
                in: path
                required: true
                description: The specified products of a chosen category
                schema: 
                    type: string
                    minimum: 1
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /product/{productId}:
        get:
            summary: Return a unique product of the catalog of products chosen
            description: A unique product
            parameters:
              - name: productId
                in: path
                required: true
                description: The specified product of the products catalog
                schema:
                    type: string
                    minimum: 1
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /register:
        get:
            summary: Returns the page of the register's page
            description: Register's page
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

        post:
            summary: Posting an user data
            consumes:
              - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: name
                type: string
                description: User's name
              - in: formData
                name: email
                type: string
                description: User's email
              - in: formData
                name: password
                type: string
                description: User's password
              - in: formData
                name: confirmPassword
                type: string
                description: User's repeat password
            responses:
                200:
                    description: OK

    /login:
        get:
            summary: Returns the page of the login page
            description: Login page of Alibazon
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html
        post:
            summary: Entering an user account
            consumes:
              - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: email
                type: string
                description: User's email
              - in: formData
                name: password
                type: string
                description: User's password
            responses:
                200:
                    description: OK
