swagger: "2.0"
info: 
    title: Alibazon Ecommerce
    description: This is my Ecommerce Application for OSF Academy
    version: 1.0
    contact: 
        email: angelo.lop.alv@gmail.com 
    license:
        name: Apache 2.0
        url: 'http://apache.org/'
    servers:
        -url: 'http://localhost:3000/'
        description: This is my local server

schemes: [http, https]

paths:
    /:
        get:
            summary: Returns the page of the men's category
            description: Men's category of Alibazon
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /category/{categoryId}:
        get:
            summary: Returns the page of the category selected
            description: Clothing categories chosen from Alibazon
            parameters:
              - name: categoryId
                in: path
                required: true
                description: The clothing category chosen
                schema:
                    type: string
                    minimum: 1        
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /products/{subcategoryId}:
        get:
            summary: Return the product catalog of the subcategory selected
            description: Product catalogs
            parameters:
              - name: subcategoryId
                in: path
                required: true
                description: The specified products of a chosen category
                schema: 
                    type: string
                    minimum: 1
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /product/{productId}:
        get:
            summary: Returns a page of the product chosen from the categories
            description: A unique product
            parameters:
              - name: productId
                in: path
                required: true
                description: The specified product of a product catalog
                schema:
                    type: string
                    minimum: 1
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

    /register:
        get:
            summary: Returns the page of the register's page
            description: Register's page
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

        post:
            summary: Posting an user data
            consumes:
              - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: name
                type: string
                description: User's name
                required: true
              - in: formData
                name: email
                type: string
                description: User's email
                required: true
              - in: formData
                name: password
                type: string
                description: User's password
                required: true
              - in: formData
                name: confirmPassword
                type: string
                description: User's repeat password
                required: true
            responses:
                200:
                    description: Success

    /login:
        get:
            summary: Returns the page of the login page
            description: Login page of Alibazon
            responses:
                200:
                    description: Success
                    schema:
                        content-type: text/html

        post:
            summary: Creating an user account
            consumes:
              - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: email
                type: string
                description: User's email
                required: true
              - in: formData
                name: password
                type: string
                description: User's password
                required: true
            responses:
                200:
                    description: Success

    /logout:
        get:
            summary: Logout an user
            responses:
                200:
                    description: Success
                401:
                    description: Unathorized, needs to login
    
    /cart:
        post:
            summary: Add a product to cart
            consumes:
            - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: productId
                type: string
                description: Product id of the product wanted
                required: true
              - in: formData
                name: variantId
                type: string
                description: Variant id of the product wanted
                required: true
              - in: quantity
                name: quantity
                type: number
                description: Quantity of the product wanted
                required: true
            responses:
                200:
                    description: Success
                401:
                    description: Unauthorized, needs to login
        get:
            summary: Returns the page of the cart's category
            description: Page of the cart
            responses:
                200:
                    description: Success
                401:
                    description: Unauthorized, needs to login
                    schema:
                        content-type: text/html
        delete:
            summary: Delete a product in a cart
            consumes:
              - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: productId
                type: string
                description: Id of the product to be deleted
                required: true 
              - in: formData
                name: variantId
                type: string
                description: Id variant to be deleted
                required: true
            responses:
                200: 
                    description: Success
                401:
                    description: Unauthorized, needs to login
    
    /cart/changeQuantity:
        get:
            summary: Change the quantity of a product
            consumes:
              - application/x-www-form-urlencoded
            parameters:
              - in: formData
                name: productId
                type: string
                description: Id of the product to be modified
                required: true
              - in: formData
                name: variantId
                type: string
                description: Variant id of the product to be modified
                required: true
              - in: quantity
                name: password
                type: number
                description: Quantity of the product to be replaced
                required: true
            responses:
                200:
                    description: Success
                401:
                    description: Unauthorized, needs to login
